"use client";

// Generated by scripts/gen-component-docs.mjs from alert-dialog.stories.tsx.
// Safe to edit — the generator never overwrites an existing file.

import { Button } from '../button';
import { AlertDialog, AlertDialogClose, AlertDialogContent, AlertDialogDescription, AlertDialogTitle, AlertDialogTrigger } from './alert-dialog';

export function Demo() {
  return (
    <AlertDialog>
      <AlertDialogTrigger render={<Button variant="danger" />}>
        Delete workspace
      </AlertDialogTrigger>
      <AlertDialogContent>
        <AlertDialogTitle className="text-base font-semibold">
          Delete workspace
        </AlertDialogTitle>
        <AlertDialogDescription className="mt-1 text-sm text-fg-muted">
          This action is permanent and cannot be undone.
        </AlertDialogDescription>
        <div className="mt-5 flex justify-end gap-2">
          <AlertDialogClose render={<Button variant="ghost" />}>
            Cancel
          </AlertDialogClose>
          <AlertDialogClose render={<Button variant="danger" />}>
            Delete
          </AlertDialogClose>
        </div>
      </AlertDialogContent>
    </AlertDialog>
  );
}
