"use client";

// Generated by scripts/gen-component-docs.mjs from combobox.stories.tsx.
// Safe to edit — the generator never overwrites an existing file.

import { Combobox, ComboboxContent, ComboboxEmpty, ComboboxInput, ComboboxItem, ComboboxList } from "./combobox";

const fruits = ["Apple", "Banana", "Cherry", "Date", "Fig", "Grape"];

export function Demo() {
  return (
    <Combobox items={fruits}>
      <ComboboxInput placeholder="Search fruits…" />
      <ComboboxContent>
        <ComboboxEmpty>No fruits found.</ComboboxEmpty>
        <ComboboxList>
          {(fruit: string) => (
            <ComboboxItem key={fruit} value={fruit}>
              {fruit}
            </ComboboxItem>
          )}
        </ComboboxList>
      </ComboboxContent>
    </Combobox>
  );
}
