"use client";

// Generated by scripts/gen-component-docs.mjs from radio-group.stories.tsx.
// Safe to edit — the generator never overwrites an existing file.

import { Radio } from '../radio/radio';
import { RadioGroup } from './radio-group';

const options = ['small', 'medium', 'large'];

export function Demo() {
  return (
    <RadioGroup defaultValue="small" aria-label="Size">
      {options.map((size) => (
        <label key={size} className="flex items-center gap-2 text-sm">
          <Radio value={size} />
          {size}
        </label>
      ))}
    </RadioGroup>
  );
}
