"use client";

// Generated by scripts/gen-component-docs.mjs from checkbox.stories.tsx.
// Safe to edit — the generator never overwrites an existing file.

import { Checkbox } from './checkbox';

export function Demo() {
  return (
    <label className="flex items-center gap-2 text-sm">
      <Checkbox />
      Accept terms
    </label>
  );
}
