"use client";

// Generated by scripts/gen-component-docs.mjs from drawer.stories.tsx.
// Safe to edit — the generator never overwrites an existing file.

import { Button } from '../button';
import { Drawer, DrawerClose, DrawerContent, DrawerDescription, DrawerTitle, DrawerTrigger } from './drawer';

export function Demo() {
  return (
    <Drawer>
      <DrawerTrigger render={<Button variant="secondary" />}>
        Open drawer
      </DrawerTrigger>
      <DrawerContent>
        <DrawerTitle className="text-base font-semibold">
          Notifications
        </DrawerTitle>
        <DrawerDescription className="mt-1 text-sm text-fg-muted">
          You are all caught up. Good job!
        </DrawerDescription>
        <div className="mt-5 flex justify-end gap-2">
          <DrawerClose render={<Button variant="ghost" />}>Close</DrawerClose>
        </div>
      </DrawerContent>
    </Drawer>
  );
}
