"use client";

// Generated by scripts/gen-component-docs.mjs from select.stories.tsx.
// Safe to edit — the generator never overwrites an existing file.

import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "./select";

const fruits = ["Apple", "Banana", "Cherry", "Date"];

export function Demo() {
  return (
    <Select defaultValue="Banana">
      <SelectTrigger>
        <SelectValue placeholder="Select a fruit" />
      </SelectTrigger>
      <SelectContent>
        {fruits.map((fruit) => (
          <SelectItem key={fruit} value={fruit}>
            {fruit}
          </SelectItem>
        ))}
      </SelectContent>
    </Select>
  );
}
