"use client";

// Generated by scripts/gen-component-docs.mjs from ai-summary.stories.tsx.
// Safe to edit — the generator never overwrites an existing file.

import { AiSummary, AiSummaryLabel, AiSummaryText } from './ai-summary';

export function Demo() {
  return (
    <AiSummary className="max-w-[342px]">
      <AiSummaryLabel>AI note</AiSummaryLabel>
      <AiSummaryText>
        Your 96th coffee this year. Same shop, same time. This one is a habit,
        not a decision.
      </AiSummaryText>
    </AiSummary>
  );
}
