"use client";

// Generated by scripts/gen-component-docs.mjs from toggle.stories.tsx.
// Safe to edit — the generator never overwrites an existing file.

import { Toggle } from './toggle';

export function Demo() {
  return (
    <Toggle aria-label="Bold">B</Toggle>
  );
}
