#!/bin/sh
# Regenerates dist/types/index.d.ts — the export surface `exportedNames()`
# resolves through package.json's "types". dist/ is gitignored, so a fresh
# clone has no index and the converter silently emits ZERO components while
# exiting 0. Run this after `npx tsc -p .design-sync/tsconfig.dts.json`.
#
# Derives from the filesystem, so a newly added component is picked up here
# automatically — but titleMap and entry.ts are still enumerated by hand.
set -eu
cd "$(git rev-parse --show-toplevel)"
mkdir -p dist/types
{
  echo '// Generated by .design-sync/gen-dts-index.sh — do not hand-edit.'
  echo '// Points at each folder barrel so multi-file components export everything.'
  ls src/components/ui | sed 's|.*|export * from "./src/components/ui/&";|'
  echo 'export * from "./src/lib/cn";'
} > dist/types/index.d.ts
echo "wrote dist/types/index.d.ts ($(grep -c '^export' dist/types/index.d.ts) exports)"
