"use client";

// Generated by scripts/gen-component-docs.mjs from otp-field.stories.tsx.
// Safe to edit — the generator never overwrites an existing file.

import * as React from 'react';
import { OTPField, OTPFieldInput } from './otp-field';

function DemoOTPField(
  props: Omit<React.ComponentProps<typeof OTPField>, 'length'>,
) {
  return (
    <OTPField {...props} length={4}>
      <OTPFieldInput />
      <OTPFieldInput />
      <OTPFieldInput />
      <OTPFieldInput />
    </OTPField>
  );
}

export function Demo() {
  return (
    <DemoOTPField />
  );
}
