"use client";

// Generated by scripts/gen-component-docs.mjs from toggle-group.stories.tsx.
// Safe to edit — the generator never overwrites an existing file.

import { Toggle } from '../toggle/toggle';
import { ToggleGroup } from './toggle-group';

export function Demo() {
  return (
    <ToggleGroup aria-label="Text alignment">
      <Toggle value="left" aria-label="Align left">
        L
      </Toggle>
      <Toggle value="center" aria-label="Align center">
        C
      </Toggle>
      <Toggle value="right" aria-label="Align right">
        R
      </Toggle>
    </ToggleGroup>
  );
}
