"use client";

// Generated by scripts/gen-component-docs.mjs from slider.stories.tsx.
// Safe to edit — the generator never overwrites an existing file.
import { Slider } from "./slider";


export function Demo() {
  return <Slider defaultValue={40} className="w-72" />;
}
