// Generated by scripts/gen-component-docs.mjs from slider.stories.tsx.
// Safe to edit — the generator never overwrites an existing file.

import { defineStory } from "@/lib/story";
import { Slider } from './slider';

export const story = defineStory({
  Component: Slider,
  args: {
    initial: { defaultValue: 40, className: 'w-72' },
  },
});
