"use client";

// Generated by scripts/gen-component-docs.mjs from meter.stories.tsx.
// Safe to edit — the generator never overwrites an existing file.

import { Meter, MeterIndicator, MeterLabel, MeterTrack, MeterValue } from './meter';

const storyArgs = { value: 40 };

export function Demo() {
  return (
    <Meter {...storyArgs} className="w-64">
      <div className="flex items-center justify-between">
        <MeterLabel>Storage used</MeterLabel>
        <MeterValue />
      </div>
      <MeterTrack>
        <MeterIndicator />
      </MeterTrack>
    </Meter>
  );
}
