"use client";

// Generated by scripts/gen-component-docs.mjs from avatar.stories.tsx.
// Safe to edit — the generator never overwrites an existing file.

import { Avatar, AvatarFallback } from './avatar';

export function Demo() {
  return (
    <Avatar>
      <AvatarFallback>MR</AvatarFallback>
    </Avatar>
  );
}
