"use client";

// Generated by scripts/gen-component-docs.mjs from scroll-area.stories.tsx.
// Safe to edit — the generator never overwrites an existing file.

import { ScrollArea, ScrollAreaScrollbar, ScrollAreaThumb, ScrollAreaViewport } from './scroll-area';

export function Demo() {
  return (
    <ScrollArea className="h-48 w-64 rounded-md border border-line">
      <ScrollAreaViewport>
        <div className="p-4 text-sm text-fg">
          {Array.from({ length: 20 }, (_, i) => (
            <p key={i} className="py-1">
              Row {i + 1}
            </p>
          ))}
        </div>
      </ScrollAreaViewport>
      <ScrollAreaScrollbar orientation="vertical">
        <ScrollAreaThumb />
      </ScrollAreaScrollbar>
    </ScrollArea>
  );
}
