"use client";

// Generated by scripts/gen-component-docs.mjs from popover.stories.tsx.
// Safe to edit — the generator never overwrites an existing file.

import { Button } from '../button';
import { Popover, PopoverContent, PopoverDescription, PopoverTitle, PopoverTrigger } from './popover';

export function Demo() {
  return (
    <Popover>
      <PopoverTrigger render={<Button variant="secondary" />}>
        Open popover
      </PopoverTrigger>
      <PopoverContent>
        <PopoverTitle className="text-sm font-semibold">
          Base UI Popover
        </PopoverTitle>
        <PopoverDescription className="mt-1 text-sm text-fg-muted">
          Portalled into the body, escaping the isolated app root.
        </PopoverDescription>
      </PopoverContent>
    </Popover>
  );
}
