"use client";

// Generated by scripts/gen-component-docs.mjs from toolbar.stories.tsx.
// Safe to edit — the generator never overwrites an existing file.

import { Toolbar, ToolbarButton, ToolbarGroup, ToolbarSeparator, ToolbarLink } from './toolbar';

export function Demo() {
  return (
    <Toolbar aria-label="Text formatting">
      <ToolbarGroup>
        <ToolbarButton>Bold</ToolbarButton>
        <ToolbarButton>Italic</ToolbarButton>
      </ToolbarGroup>
      <ToolbarSeparator />
      <ToolbarLink href="#">Docs</ToolbarLink>
    </Toolbar>
  );
}
