"use client";

// Generated by scripts/gen-component-docs.mjs from form.stories.tsx.
// Safe to edit — the generator never overwrites an existing file.

import { Form } from './form';
import { Field, FieldLabel, FieldControl, FieldError } from '../field/field';
import { Button } from '../button/button';

export function Demo() {
  return (
    <Form
      onFormSubmit={(values, eventDetails) => {
        eventDetails.event?.preventDefault?.();
      }}
    >
      <Field name="name">
        <FieldLabel>Name</FieldLabel>
        <FieldControl required placeholder="Ada Lovelace" />
        <FieldError />
      </Field>
      <Button type="submit">Submit</Button>
    </Form>
  );
}
