"use client";

// Generated by scripts/gen-component-docs.mjs from autocomplete.stories.tsx.
// Safe to edit — the generator never overwrites an existing file.

import { Autocomplete, AutocompleteContent, AutocompleteEmpty, AutocompleteInput, AutocompleteItem, AutocompleteList } from "./autocomplete";

const fruits = ["Apple", "Banana", "Cherry", "Date", "Fig", "Grape"];

export function Demo() {
  return (
    <Autocomplete items={fruits}>
      <AutocompleteInput placeholder="Search fruits…" />
      <AutocompleteContent>
        <AutocompleteEmpty>No fruits found.</AutocompleteEmpty>
        <AutocompleteList>
          {(fruit: string) => (
            <AutocompleteItem key={fruit} value={fruit}>
              {fruit}
            </AutocompleteItem>
          )}
        </AutocompleteList>
      </AutocompleteContent>
    </Autocomplete>
  );
}
