"use client";

// Generated by scripts/gen-component-docs.mjs from tooltip.stories.tsx.
// Safe to edit — the generator never overwrites an existing file.
import { Tooltip } from "./tooltip";

import { Button } from '../button';

export function Demo() {
  return <Tooltip content="Styled with design tokens"><Button variant="secondary">Hover me</Button></Tooltip>;
}
