// Generated by scripts/gen-component-docs.mjs from tooltip.stories.tsx.
// Safe to edit — the generator never overwrites an existing file.

import { defineStory } from "@/lib/story";
import { Button } from '../button';
import { Tooltip } from './tooltip';

export const story = defineStory({
  Component: Tooltip,
  args: {
    initial: {
    content: 'Styled with design tokens',
    children: <Button variant="secondary">Hover me</Button>,
  },
  },
});
