"use client";

// Generated by scripts/gen-component-docs.mjs from field.stories.tsx.
// Safe to edit — the generator never overwrites an existing file.

import { Field, FieldLabel, FieldDescription, FieldControl } from './field';

export function Demo() {
  return (
    <Field name="email">
      <FieldLabel>Email</FieldLabel>
      <FieldControl type="email" placeholder="you@example.com" />
      <FieldDescription>We&apos;ll never share your email.</FieldDescription>
    </Field>
  );
}
