// Generated by scripts/gen-component-docs.mjs from button.stories.tsx.
// Safe to edit — the generator never overwrites an existing file.

import { defineStory } from "@/lib/story";
import { Button } from "./button.demo";

export const story = defineStory({
  Component: Button,
  args: {
    initial: { children: 'Save changes' },
  },
});
