"use client";

// Generated by scripts/gen-component-docs.mjs from button.stories.tsx.
// Safe to edit — the generator never overwrites an existing file.
import { Button } from "./button";
export { Button };


export function Demo() {
  return <Button>Save changes</Button>;
}
