"use client";

// Generated by scripts/gen-component-docs.mjs from button.stories.tsx.
// Safe to edit — the generator never overwrites an existing file.
import * as React from "react";
import { Button, type ButtonProps } from "./button";
export { Button };

export function Demo() {
  return <Button>Save changes</Button>;
}

/* -------------------------------------------------------------- states -- */

const VARIANTS = ["primary", "secondary", "ghost", "danger"] as const;

/**
 * Hover and focus can't be photographed from a real pointer, so those two
 * columns force the state with the SAME utility the component applies for it.
 * Mirrored from button.tsx — if a variant's hover token changes there, change
 * it here too. Default and Disabled are the real thing: no forcing, `disabled`
 * is the actual prop.
 */
const FORCED_HOVER: Record<(typeof VARIANTS)[number], string> = {
  primary: "bg-accent-hover",
  secondary: "bg-surface",
  ghost: "bg-surface",
  danger: "opacity-90",
};

const FORCED_FOCUS = "outline-2 outline-offset-2 outline-ring";

const COLUMNS = ["Default", "Hover", "Focus", "Disabled"] as const;

function Cell({
  variant,
  state,
}: {
  variant: (typeof VARIANTS)[number];
  state: (typeof COLUMNS)[number];
}) {
  const props: ButtonProps = { variant, children: "Save" };
  if (state === "Hover") props.className = FORCED_HOVER[variant];
  if (state === "Focus") props.className = FORCED_FOCUS;
  if (state === "Disabled") props.disabled = true;
  return <Button {...props} />;
}

export function ButtonStates() {
  return (
    <div className="overflow-x-auto">
      <div
        className="grid min-w-[520px] items-center gap-x-4 gap-y-3"
        style={{ gridTemplateColumns: "5.5rem repeat(4, 1fr)" }}
      >
        <span />
        {COLUMNS.map((c) => (
          <span
            key={c}
            className="font-mono text-[10.5px] tracking-[0.08em] text-fg-subtle uppercase"
          >
            {c}
          </span>
        ))}

        {VARIANTS.map((variant) => (
          // Fragment needs the key: it is what the map returns, so a key on an
          // inner child would not satisfy React.
          <React.Fragment key={variant}>
            <span className="font-mono text-xs text-fg">{variant}</span>
            {COLUMNS.map((state) => (
              <div key={state} className="flex">
                <Cell variant={variant} state={state} />
              </div>
            ))}
          </React.Fragment>
        ))}
      </div>
    </div>
  );
}
