"use client";

// Generated by scripts/gen-component-docs.mjs from progress.stories.tsx.
// Safe to edit — the generator never overwrites an existing file.

import { Progress, ProgressIndicator, ProgressLabel, ProgressTrack, ProgressValue } from './progress';

const storyArgs = { value: 60 };

export function Demo() {
  return (
    <Progress {...storyArgs} className="w-64">
      <div className="flex items-center justify-between">
        <ProgressLabel>Uploading</ProgressLabel>
        <ProgressValue />
      </div>
      <ProgressTrack>
        <ProgressIndicator />
      </ProgressTrack>
    </Progress>
  );
}
