"use client";

// Generated by scripts/gen-component-docs.mjs from accordion.stories.tsx.
// Safe to edit — the generator never overwrites an existing file.

import { Accordion, AccordionItem, AccordionTrigger, AccordionPanel } from './accordion';

const items = [
  {
    value: 'tokens',
    title: 'What are design tokens?',
    body: 'Named values for color, type, spacing, and motion that keep the system consistent.',
  },
  {
    value: 'primitives',
    title: 'Why Base UI?',
    body: 'Unstyled, accessible primitives that leave every visual decision to the token layer.',
  },
  {
    value: 'theming',
    title: 'How does dark mode work?',
    body: 'Semantic tokens flip under the .dark class, so components never change.',
  },
];

export function Demo() {
  return (
    <Accordion className="w-96">
      {items.map((item) => (
        <AccordionItem key={item.value} value={item.value}>
          <AccordionTrigger>{item.title}</AccordionTrigger>
          <AccordionPanel>{item.body}</AccordionPanel>
        </AccordionItem>
      ))}
    </Accordion>
  );
}
