"use client";

// Generated by scripts/gen-component-docs.mjs from dialog.stories.tsx.
// Safe to edit — the generator never overwrites an existing file.

import { Button } from '../button';
import { Dialog, DialogClose, DialogContent, DialogDescription, DialogTitle, DialogTrigger } from './dialog';

export function Demo() {
  return (
    <Dialog>
      <DialogTrigger render={<Button variant="secondary" />}>
        Open dialog
      </DialogTrigger>
      <DialogContent>
        <DialogTitle className="text-base font-semibold">
          Delete workspace
        </DialogTitle>
        <DialogDescription className="mt-1 text-sm text-fg-muted">
          This action is permanent and cannot be undone.
        </DialogDescription>
        <div className="mt-5 flex justify-end gap-2">
          <DialogClose render={<Button variant="ghost" />}>
            Cancel
          </DialogClose>
          <DialogClose render={<Button variant="danger" />}>
            Delete
          </DialogClose>
        </div>
      </DialogContent>
    </Dialog>
  );
}
