"use client";

// Generated by scripts/gen-component-docs.mjs from checkbox-group.stories.tsx.
// Safe to edit — the generator never overwrites an existing file.

import { Checkbox } from '../checkbox/checkbox';
import { CheckboxGroup } from './checkbox-group';

const fruits = ['apple', 'banana', 'cherry'];

export function Demo() {
  return (
    <CheckboxGroup aria-label="Fruits">
      {fruits.map((fruit) => (
        <label key={fruit} className="flex items-center gap-2 text-sm">
          <Checkbox name={fruit} />
          {fruit}
        </label>
      ))}
    </CheckboxGroup>
  );
}
