// Generated by scripts/gen-component-docs.mjs from toast.stories.tsx.
// Safe to edit — the generator never overwrites an existing file.

import { defineStory } from "@/lib/story";
import { Demo } from "./toast.demo";

export const story = defineStory({
  Component: Demo,
  args: {
    initial: {},
  },
});
