"use client";

// Generated by scripts/gen-component-docs.mjs from toast.stories.tsx.
// Safe to edit — the generator never overwrites an existing file.

import { Button } from "../button";
import { Toast, ToastClose, ToastDescription, ToastProvider, ToastTitle, ToastViewport, useToast, useToastManager } from "./toast";

let stackCount = 0;
function ToastList() {
  const { toasts } = useToastManager();

  return (
    <ToastViewport>
      {toasts.map((toast) => (
        <Toast key={toast.id} toast={toast}>
          <ToastTitle>{toast.title}</ToastTitle>
          <ToastDescription>{toast.description}</ToastDescription>
          <ToastClose aria-label="Dismiss">
            <svg viewBox="0 0 12 12" fill="none" className="size-3">
              <path
                d="M2 2L10 10M10 2L2 10"
                stroke="currentColor"
                strokeWidth="1.5"
                strokeLinecap="round"
              />
            </svg>
          </ToastClose>
        </Toast>
      ))}
    </ToastViewport>
  );
}
function StackingDemo() {
  const { add } = useToast();

  return (
    <Button
      variant="secondary"
      onClick={() =>
        add({
          title: `Changes saved (#${++stackCount})`,
          description: "Each click appends a toast to the stack.",
        })
      }
    >
      Add toast
    </Button>
  );
}

export function Demo() {
  return (
    <ToastProvider>
      <StackingDemo />
      <ToastList />
    </ToastProvider>
  );
}
