"use client";

// Generated by scripts/gen-component-docs.mjs from badge.stories.tsx.
// Safe to edit — the generator never overwrites an existing file.

import { Badge } from './badge';

export function Demo() {
  return (
    <div className="flex flex-wrap gap-2">
      <Badge tone="success">Paid</Badge>
      <Badge tone="info">Pending</Badge>
      <Badge tone="warning">Retrying</Badge>
      <Badge tone="danger">Overdue</Badge>
      <Badge>Draft</Badge>
    </div>
  );
}
