"use client";

// Generated by scripts/gen-component-docs.mjs from switch.stories.tsx.
// Safe to edit — the generator never overwrites an existing file.
import { Switch } from "./switch";


export function Demo() {
  return <Switch aria-label="Toggle setting" />;
}
