// Generated by scripts/gen-component-docs.mjs from switch.stories.tsx.
// Safe to edit — the generator never overwrites an existing file.

import { defineStory } from "@/lib/story";
import { Switch } from './switch';

export const story = defineStory({
  Component: Switch,
  args: {
    initial: {
      "aria-label": "Toggle setting",
    },
  },
});
