// Generated by scripts/gen-component-docs.mjs from input.stories.tsx.
// Safe to edit — the generator never overwrites an existing file.

import { defineStory } from "@/lib/story";
import { Input } from './input';

export const story = defineStory({
  Component: Input,
  args: {
    initial: {
    placeholder: 'Enter text…',
  },
  },
});
