"use client";

// Generated by scripts/gen-component-docs.mjs from input.stories.tsx.
// Safe to edit — the generator never overwrites an existing file.
import { Input } from "./input";


export function Demo() {
  return <Input placeholder="Enter text…" />;
}
