"use client";

// Generated by scripts/gen-component-docs.mjs from banner.stories.tsx.
// Safe to edit — the generator never overwrites an existing file.

import { Banner } from './banner';

export function Demo() {
  return (
    <div className="flex w-[560px] flex-col gap-2.5">
      <Banner tone="info">
        Hover and focus can&rsquo;t come from a real pointer here, so those two
        columns are forced with the same utility the component uses.
      </Banner>
      <Banner tone="warning">
        Two props on this page are deprecated and removed in 0.2. The table
        still documents them.
      </Banner>
      <Banner tone="success">
        The registry rebuilt cleanly and all 41 items validated.
      </Banner>
      <Banner tone="danger">
        This table was generated against 0.0.9. Three variants have changed
        since &mdash; regenerate before citing it.
      </Banner>
    </div>
  );
}
