"use client";

// Generated by scripts/gen-component-docs.mjs from fieldset.stories.tsx.
// Safe to edit — the generator never overwrites an existing file.

import { Fieldset, FieldsetLegend } from './fieldset';
import { Field, FieldLabel, FieldControl } from '../field/field';

export function Demo() {
  return (
    <Fieldset>
      <FieldsetLegend>Shipping address</FieldsetLegend>
      <Field name="street">
        <FieldLabel>Street</FieldLabel>
        <FieldControl placeholder="123 Main St" />
      </Field>
      <Field name="city">
        <FieldLabel>City</FieldLabel>
        <FieldControl placeholder="Metropolis" />
      </Field>
    </Fieldset>
  );
}
