"use client";

// Generated by scripts/gen-component-docs.mjs from collapsible.stories.tsx.
// Safe to edit — the generator never overwrites an existing file.

import { Collapsible, CollapsibleTrigger, CollapsiblePanel } from './collapsible';

export function Demo() {
  return (
    <Collapsible className="w-96">
      <CollapsibleTrigger>What is a collapsible?</CollapsibleTrigger>
      <CollapsiblePanel>
        A single disclosure region that toggles between an open and closed
        state.
      </CollapsiblePanel>
    </Collapsible>
  );
}
