"use client";

// Generated by scripts/gen-component-docs.mjs from radio.stories.tsx.
// Safe to edit — the generator never overwrites an existing file.

import { RadioGroup } from '../radio-group/radio-group';
import { Radio } from './radio';

export function Demo() {
  return (
    <RadioGroup defaultValue="small" aria-label="Size">
      {['small', 'medium', 'large'].map((size) => (
        <label key={size} className="flex items-center gap-2 text-sm">
          <Radio value={size} />
          {size}
        </label>
      ))}
    </RadioGroup>
  );
}
