"use client";

// Generated by scripts/gen-component-docs.mjs from separator.stories.tsx.
// Safe to edit — the generator never overwrites an existing file.

import { Separator } from './separator';

export function Demo() {
  return (
    <div className="w-64 text-sm text-fg">
      <div>Above</div>
      <Separator className="my-3" />
      <div>Below</div>
    </div>
  );
}
