"use client";

// Generated by scripts/gen-component-docs.mjs from number-field.stories.tsx.
// Safe to edit — the generator never overwrites an existing file.

import * as React from 'react';
import { NumberField, NumberFieldGroup, NumberFieldInput, NumberFieldIncrement, NumberFieldDecrement } from './number-field';

function DemoNumberField(props: React.ComponentProps<typeof NumberField>) {
  return (
    <NumberField defaultValue={10} {...props}>
      <NumberFieldGroup>
        <NumberFieldDecrement>−</NumberFieldDecrement>
        <NumberFieldInput />
        <NumberFieldIncrement>+</NumberFieldIncrement>
      </NumberFieldGroup>
    </NumberField>
  );
}

export function Demo() {
  return (
    <DemoNumberField />
  );
}
