"use client";

// Generated by scripts/gen-component-docs.mjs from preview-card.stories.tsx.
// Safe to edit — the generator never overwrites an existing file.

import { PreviewCard, PreviewCardContent, PreviewCardTrigger } from './preview-card';

export function Demo() {
  return (
    <PreviewCard>
      <PreviewCardTrigger
        href="#"
        delay={0}
        className="text-fg underline decoration-line-strong underline-offset-2 outline-none focus-visible:outline-2 focus-visible:outline-ring"
      >
        @sprout-team
      </PreviewCardTrigger>
      <PreviewCardContent>
        <p className="text-sm font-semibold">Sprout Team</p>
        <p className="mt-1 text-sm text-fg-muted">
          Design system maintainers. Hover to preview, click to visit.
        </p>
      </PreviewCardContent>
    </PreviewCard>
  );
}
