"use client";

// Generated by scripts/gen-component-docs.mjs from menu.stories.tsx.
// Safe to edit — the generator never overwrites an existing file.

import { Button } from '../button';
import { Menu, MenuContent, MenuItem, MenuSeparator, MenuTrigger } from './menu';

export function Demo() {
  return (
    <Menu>
      <MenuTrigger render={<Button variant="secondary" />}>
        Open menu
      </MenuTrigger>
      <MenuContent>
        <MenuItem>New file</MenuItem>
        <MenuItem>New window</MenuItem>
        <MenuSeparator />
        <MenuItem>Rename</MenuItem>
        <MenuItem>Duplicate</MenuItem>
        <MenuSeparator />
        <MenuItem disabled>Delete</MenuItem>
      </MenuContent>
    </Menu>
  );
}
