"use client";

// Generated by scripts/gen-component-docs.mjs from tabs.stories.tsx.
// Safe to edit — the generator never overwrites an existing file.

import { Tabs, TabsList, TabsTab, TabsPanel } from './tabs';

export function Demo() {
  return (
    <Tabs defaultValue="tokens" className="w-96">
      <TabsList>
        {['tokens', 'components', 'patterns'].map((value) => (
          <TabsTab key={value} value={value}>
            {value}
          </TabsTab>
        ))}
      </TabsList>
      <TabsPanel value="tokens">
        Color, typography, spacing, and motion tokens.
      </TabsPanel>
      <TabsPanel value="components">
        Base UI primitives styled with the token layer.
      </TabsPanel>
      <TabsPanel value="patterns">
        Composition patterns built from components.
      </TabsPanel>
    </Tabs>
  );
}
